package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

public class LoginScherm2Controller extends GridPane {
	@FXML
	private Button btnInloggen;
	@FXML
	private Button btnAnnuleer;
	@FXML
	private PasswordField pwfWachtwoord;
	@FXML
	private TextField txfGebruikersnaam;
	@FXML
	private Label lblMessage;

	public LoginScherm2Controller() {
		super();
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginScherm2.fxml"));
            loader.setController(this);
            loader.setRoot(this);
            loader.load();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
	}
	// Event Listener on Button[#btnInloggen].onAction
	@FXML
	public void btnInloggenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnnuleer].onAction
	@FXML
	public void btnAnnuleerAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
